export const products = [
  {
    id: 1,
    descripcionProducto: "Entregar 50 mesas a Home Depot",
    chofer: "Luis Hernandez",
    fechaEntrega: "2023-01-01",
    noCamioneta: "ABC123",
    CalleNumeroColonia: "Av. Reforma #123, Col. Centro",
    entidadFederativaAlcaldia: "Ciudad de México",
    imagenes: ["url1.jpg", "url2.jpg", "url3.jpg"],
    estado: "Entregado",
    acompanantes: ["María Sánchez", "Jorge Ramírez"],
  },
  {
    id: 2,
    descripcionProducto: "Surtir de 80 sillas a Walmart",
    chofer: "Ana Gomez",
    fechaEntrega: "2023-01-02",
    noCamioneta: "XYZ456",
    CalleNumeroColonia: "Calle Juárez #456, Col. Juárez",
    entidadFederativaAlcaldia: "Monterrey, Nuevo León",
    imagenes: ["url4.jpg", "url5.jpg", "url6.jpg"],
    estado: "En camino",
    acompanantes: ["Carlos Torres"],
  },
  {
    id: 3,
    descripcionProducto: "Entrega de 100 lámparas a Liverpool",
    chofer: "Martin Ramirez",
    fechaEntrega: "2023-01-03",
    noCamioneta: "DEF789",
    CalleNumeroColonia: "Av. Constitución #789, Col. Constitución",
    entidadFederativaAlcaldia: "Guadalajara, Jalisco",
    imagenes: ["url7.jpg", "url8.jpg", "url9.jpg"],
    estado: "Pendiente",
    acompanantes: ["Lucía Pérez", "Héctor Rodríguez"],
  },
  {
    id: 4,
    descripcionProducto: "Envío de 30 televisores a Soriana",
    chofer: "Sofía Torres",
    fechaEntrega: "2023-01-04",
    noCamioneta: "GHI012",
    CalleNumeroColonia: "Calle Morelos #012, Col. Morelos",
    entidadFederativaAlcaldia: "Puebla, Puebla",
    imagenes: ["url10.jpg", "url11.jpg", "url12.jpg"],
    estado: "Con problemas",
    acompanantes: ["Diego Soto", "Elena Rodríguez"],
  },
  {
    id: 5,
    descripcionProducto: "Entrega de 200 productos de belleza a Sears",
    chofer: "Roberto Sánchez",
    fechaEntrega: "2023-01-05",
    noCamioneta: "JKL345",
    CalleNumeroColonia: "Av. Hidalgo #345, Col. Hidalgo",
    entidadFederativaAlcaldia: "Tijuana, Baja California",
    imagenes: ["url13.jpg", "url14.jpg", "url15.jpg"],
    estado: "Entregado",
    acompanantes: ["Fernanda Torres"],
  },
  {
    id: 6,
    descripcionProducto: "Recoger 40 equipos deportivos en Decathlon",
    chofer: "Elena Martínez",
    fechaEntrega: "2023-01-06",
    noCamioneta: "MNO678",
    CalleNumeroColonia: "Calle Revolución #678, Col. Revolución",
    entidadFederativaAlcaldia: "Ciudad de México",
    imagenes: ["url16.jpg", "url17.jpg", "url18.jpg"],
    estado: "En camino",
    acompanantes: ["Javier Rodríguez", "Roberto Pérez", "Ana Rodríguez"],
  },
  {
    id: 7,
    descripcionProducto: "Envío de 50 productos alimenticios a Sam's Club",
    chofer: "aldrich",
    fechaEntrega: "2023-01-07",
    noCamioneta: "PQR901",
    CalleNumeroColonia: "Av. Independencia #901, Col. Independencia",
    entidadFederativaAlcaldia: "Guadalajara, Jalisco",
    imagenes: ["url19.jpg", "url20.jpg", "url21.jpg"],
    estado: "Con problemas",
    acompanantes: ["Javier Pérez", "Ana Ramírez"],
  },
  {
    id: 8,
    descripcionProducto: "Entrega de 60 equipos de cocina a Liverpool",
    chofer: "Valentina Martínez",
    fechaEntrega: "2023-01-08",
    noCamioneta: "STU234",
    CalleNumeroColonia: "Calle Morelos #234, Col. Morelos",
    entidadFederativaAlcaldia: "Puebla, Puebla",
    imagenes: ["url22.jpg", "url23.jpg", "url24.jpg"],
    estado: "Pendiente",
    acompanantes: ["Fernando Soto", "Elena Ramírez"],
  },
  {
    id: 9,
    descripcionProducto: "Envío de 25 computadoras a Office Depot",
    chofer: "Javier Ramírez",
    fechaEntrega: "2023-01-09",
    noCamioneta: "VWX567",
    CalleNumeroColonia: "Av. Reforma #567, Col. Reforma",
    entidadFederativaAlcaldia: "Monterrey, Nuevo León",
    imagenes: ["url25.jpg", "url26.jpg", "url27.jpg"],
    estado: "Entregado",
    acompanantes: ["Isabel Gómez"],
  },
  {
    id: 10,
    descripcionProducto: "Recoger 30 teléfonos en Telcel",
    chofer: "Fernando Torres",
    fechaEntrega: "2023-01-10",
    noCamioneta: "YZA890",
    CalleNumeroColonia: "Calle Juárez #890, Col. Juárez",
    entidadFederativaAlcaldia: "Tijuana, Baja California",
    imagenes: ["url28.jpg", "url29.jpg", "url30.jpg"],
    estado: "Pendiente",
    acompanantes: ["Lucía Pérez", "Héctor Rodríguez"],
  },
  {
    id: 11,
    descripcionProducto: "Entrega de 50 sillas a Walmart",
    chofer: "Karla Sánchez",
    fechaEntrega: "2023-01-11",
    noCamioneta: "ABC123",
    CalleNumeroColonia: "Av. Insurgentes #123, Col. Insurgentes",
    entidadFederativaAlcaldia: "Ciudad de México, CDMX",
    imagenes: ["url31.jpg", "url32.jpg", "url33.jpg"],
    estado: "En camino",
    acompanantes: ["Miguel García", "Sofía González", "Luis Rodríguez"],
  },
  {
    id: 12,
    descripcionProducto: "Recoger mercancía en Liverpool",
    chofer: "Alejandro López",
    fechaEntrega: "2023-01-12",
    noCamioneta: "XYZ456",
    CalleNumeroColonia: "Calle Reforma #456, Col. Reforma",
    entidadFederativaAlcaldia: "Guadalajara, Jalisco",
    imagenes: ["url34.jpg", "url35.jpg", "url36.jpg"],
    estado: "Pendiente",
    acompanantes: ["Rosa Martínez", "Daniel Gómez"],
  },
  {
    id: 13,
    descripcionProducto: "Realizar entrega especial de regalos",
    chofer: "Carlos González",
    fechaEntrega: "2023-01-13",
    noCamioneta: "DEF789",
    CalleNumeroColonia: "Av. Revolución #789, Col. Revolución",
    entidadFederativaAlcaldia: "Monterrey, Nuevo León",
    imagenes: ["url37.jpg", "url38.jpg", "url39.jpg"],
    estado: "Entregado",
    acompanantes: ["Ana Rodríguez", "José Pérez"],
  },
  {
    id: 14,
    descripcionProducto: "Revisar inventario en bodega",
    chofer: "María Hernández",
    fechaEntrega: "2023-01-14",
    noCamioneta: "GHI012",
    CalleNumeroColonia: "Calle Hidalgo #012, Col. Hidalgo",
    entidadFederativaAlcaldia: "Puebla, Puebla",
    imagenes: ["url40.jpg", "url41.jpg", "url42.jpg"],
    estado: "En camino",
    acompanantes: ["Fernando Soto"],
  },
  {
    id: 15,
    descripcionProducto: "Coordinar logística de envíos",
    chofer: "Leonardo Ramirez",
    fechaEntrega: "2023-01-15",
    noCamioneta: "JKL345",
    CalleNumeroColonia: "Av. Juárez #345, Col. Juárez",
    entidadFederativaAlcaldia: "Tijuana, Baja California",
    imagenes: ["url43.jpg", "url44.jpg", "url45.jpg"],
    estado: "Pendiente",
    acompanantes: ["Isabel Gómez", "Miguel García"],
  },
  {
    id: 16,
    descripcionProducto: "Entrega de juguetes",
    chofer: "Leonardo Ramirez",
    fechaEntrega: "2023-01-16",
    noCamioneta: "MNO901",
    CalleNumeroColonia: "Av. Reforma Sur #567, Col. Providencia",
    entidadFederativaAlcaldia: "Monterrey, Nuevo León",
    imagenes: ["url46.jpg", "url47.jpg", "url48.jpg"],
    estado: "Pendiente",
    acompanantes: ["Isabel Gómez", "Fernando Soto"],
  },
  {
    id: 17,
    descripcionProducto: "Realizar análisis de mercado",
    chofer: "Gabriela Soto",
    fechaEntrega: "2023-01-17",
    noCamioneta: "PQR901",
    CalleNumeroColonia: "Calle Morelos #901, Col. Morelos",
    entidadFederativaAlcaldia: "Puebla, Puebla",
    imagenes: ["url49.jpg", "url50.jpg", "url51.jpg"],
    estado: "En camino",
    acompanantes: ["Lucía Pérez", "Sofía González"],
  },
  {
    id: 18,
    descripcionProducto: "Preparar informe de ventas",
    chofer: "Gabriela Soto",
    fechaEntrega: "2023-01-18",
    noCamioneta: "STU234",
    CalleNumeroColonia: "Av. Hidalgo #234, Col. Hidalgo",
    entidadFederativaAlcaldia: "Ciudad de México, CDMX",
    imagenes: ["url52.jpg", "url53.jpg", "url54.jpg"],
    estado: "Pendiente",
    acompanantes: ["Luis Rodríguez", "Ana Rodríguez"],
  },
  {
    id: 19,
    descripcionProducto: "Coordinar reunión de equipo",
    chofer: "Gabriela Soto",
    fechaEntrega: "2023-01-19",
    noCamioneta: "VWX567",
    CalleNumeroColonia: "Av. Juárez #567, Col. Juárez",
    entidadFederativaAlcaldia: "Tijuana, Baja California",
    imagenes: ["url55.jpg", "url56.jpg", "url57.jpg"],
    estado: "Entregado",
    acompanantes: ["Miguel García", "Isabel Gómez"],
  },
  {
    id: 20,
    descripcionProducto: "Enviar propuestas a clientes",
    chofer: "Gabriela Soto",
    fechaEntrega: "2023-01-20",
    noCamioneta: "YZA890",
    CalleNumeroColonia: "Calle Reforma #890, Col. Reforma",
    entidadFederativaAlcaldia: "Guadalajara, Jalisco",
    imagenes: ["url58.jpg", "url59.jpg", "url60.jpg"],
    estado: "Pendiente",
    acompanantes: ["Sofía González", "Fernando Soto"],
  },
];
