export const products = [
  {
    id: 1,
    titulo: "Producto 1",
    chofer: "Chofer 1",
    fecha: "2023-01-01",
    noCamioneta: "ABC123",
    imagenes: ["url1.jpg", "url2.jpg", "url3.jpg"],
    estado: "Entregado",
  },
  {
    id: 2,
    titulo: "Producto 2",
    chofer: "Chofer 2",
    fecha: "2023-01-02",
    noCamioneta: "XYZ456",
    imagenes: ["url4.jpg", "url5.jpg", "url6.jpg"],
    estado: "En camino",
  },
  {
    id: 3,
    titulo: "Producto 3",
    chofer: "Chofer 3",
    fecha: "2023-01-03",
    noCamioneta: "DEF789",
    imagenes: ["url7.jpg", "url8.jpg", "url9.jpg"],
    estado: "Pendiente",
  },
  {
    id: 4,
    titulo: "Producto 4",
    chofer: "Chofer 4",
    fecha: "2023-01-04",
    noCamioneta: "GHI012",
    imagenes: ["url10.jpg", "url11.jpg", "url12.jpg"],
    estado: "Con problemas",
  },
  {
    id: 5,
    titulo: "Producto 5",
    chofer: "Chofer 5",
    fecha: "2023-01-05",
    noCamioneta: "JKL345",
    imagenes: ["url13.jpg", "url14.jpg", "url15.jpg"],
    estado: "Entregado",
  },
  {
    id: 6,
    titulo: "Producto 6",
    chofer: "Chofer 6",
    fecha: "2023-01-06",
    noCamioneta: "MNO678",
    imagenes: ["url16.jpg", "url17.jpg", "url18.jpg"],
    estado: "En camino",
  },
  {
    id: 7,
    titulo: "Producto 7",
    chofer: "Chofer 7",
    fecha: "2023-01-07",
    noCamioneta: "PQR901",
    imagenes: ["url19.jpg", "url20.jpg", "url21.jpg"],
    estado: "Pendiente",
  },
  {
    id: 8,
    titulo: "Producto 8",
    chofer: "Chofer 8",
    fecha: "2023-01-08",
    noCamioneta: "STU234",
    imagenes: ["url22.jpg", "url23.jpg", "url24.jpg"],
    estado: "Con problemas",
  },
  {
    id: 9,
    titulo: "Producto 9",
    chofer: "Chofer 9",
    fecha: "2023-01-09",
    noCamioneta: "VWX567",
    imagenes: ["url25.jpg", "url26.jpg", "url27.jpg"],
    estado: "Entregado",
  },
  {
    id: 10,
    titulo: "Producto 10",
    chofer: "Chofer 10",
    fecha: "2023-01-10",
    noCamioneta: "YZA890",
    imagenes: ["url28.jpg", "url29.jpg", "url30.jpg"],
    estado: "Pendiente",
  },
];
